format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
${custom.vi_prompt}\
$character
"""

[custom.vi_prompt]
command = "echo $ZVM_CUSTOM_MODE_PROMPT_CHAR"
when = "true"
format = "[$symbol($output)](yellow) "

[character]
success_symbol = '[î˜‚](bold green)'
error_symbol = '[î˜‚](bold red)'
vimcmd_symbol = '[î˜‚](bold yellow)'

[aws]
format = 'ó°” [$symbol($profile)(\($region\))(ó°” $duration\])]($style)\]'
symbol = "îŒ½  "

[bun]
format = 'ó°” [$symbol($version)]($style)\]'

[c]
format = 'ó°” [$symbol($version(-$name))]($style)\]'
symbol = "î˜ "

[cmake]
format = 'ó°” [$symbol($version)]($style)\]'

[cmd_duration]
format = 'ó°” [â± $duration]($style)\]'

[cobol]
format = 'ó°” [$symbol($version)]($style)\]'

[conda]
format = 'ó°” [$symbol$environment]($style)\]'
symbol = "ï„Œ "

[crystal]
format = 'ó°” [$symbol($version)]($style)\]'

[daml]
format = 'ó°” [$symbol($version)]($style)\]'

[dart]
format = 'ó°” [$symbol($version)]($style)\]'
symbol = "î˜ "

[deno]
format = 'ó°” [$symbol($version)]($style)\]'

[docker_context]
format = 'ó°” [$symbol$context]($style)\]'
symbol = "ïŒˆ "

[dotnet]
format = 'ó°” [$symbol($version)(ğŸ¯ $tfm)]($style)\]'

[elixir]
format = 'ó°” [$symbol($version \(OTP $otp_version\))]($style)\]'
symbol = "î‰µ "

[elm]
format = 'ó°” [$symbol($version)]($style)\]'
symbol = "î˜¬ "

[erlang]
format = 'ó°” [$symbol($version)]($style)\]'

[fennel]
format = 'ó°” [$symbol($version)]($style)\]'

[fossil_branch]
format = 'ó°” [$symbol$branch]($style)\]'
symbol = "ï˜ "

[gcloud]
format = 'ó°” [$symbol$account(@$domain)(\($region\))]($style)\]'

[git_branch]
format = ' on ó°” [$symbol$branch]($style)\]'
symbol = "ï˜ "

[git_status]
format = '([ó°” $all_status$ahead_behind\]]($style))'

[golang]
format = 'ó°” [$symbol($version)]($style)\]'
symbol = "î˜§ "

[gradle]
format = 'ó°” [$symbol($version)]($style)\]'

[guix_shell]
format = 'ó°” [$symbol]($style)\]'
symbol = "ïŒ¥ "

[haskell]
format = 'ó°” [$symbol($version)]($style)\]'
symbol = "î· "

[haxe]
format = 'ó°” [$symbol($version)]($style)\]'
symbol = "âŒ˜ "

[helm]
format = 'ó°” [$symbol($version)]($style)\]'

[hg_branch]
format = 'ó°” [$symbol$branch]($style)\]'
symbol = "ï˜ "

[hostname]
ssh_symbol = "î¬ "

[java]
format = 'ó°” [$symbol($version)]($style)\]'
symbol = "î‰– "

[julia]
format = 'ó°” [$symbol($version)]($style)\]'
symbol = "î˜¤ "

[kotlin]
format = 'ó°” [$symbol($version)]($style)\]'

[kubernetes]
format = 'ó°” [$symbol$context( \($namespace\))]($style)\]'

[directory]
read_only = " ó°Œ¾"

[lua]
format = 'ó°” [$symbol($version)]($style)\]'
symbol = "î˜  "

[memory_usage]
format = 'ó°” $symbol[$ram( | $swap)]($style)\]'
symbol = "ó°› "

[meson]
format = 'ó°” [$symbol$project]($style)\]'
symbol = "ó°”· "

[nim]
format = 'ó°” [$symbol($version)]($style)\]'
symbol = "ó°†¥ "

[nix_shell]
format = 'ó°” [$symbol$state( \($name\))]($style)\]'
symbol = "ïŒ“ "

[nodejs]
format = 'ó°” [$symbol($version)]($style)\]'
symbol = "îœ˜ "

[ocaml]
format = 'ó°” [$symbol($version)(\($switch_indicator$switch_name\))]($style)\]'

[opa]
format = 'ó°” [$symbol($version)]($style)\]'

[openstack]
format = 'ó°” [$symbol$cloud(\($project\))]($style)\]'

[os.symbols]
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ó°ˆ¸ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
Redox = "ó°€˜ "
Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Windows = "ó°² "

[os]
format = 'ó°” [$symbol]($style)\]'

[package]
format = 'ó°” [$symbol$version]($style)\]'
symbol = "ó°— "

[perl]
format = 'ó°” [$symbol($version)]($style)\]'

[php]
format = 'ó°” [$symbol($version)]($style)\]'

[pijul_channel]
format = 'ó°” [$symbol$channel]($style)\]'
symbol = "ğŸªº "

[pulumi]
format = 'ó°” [$symbol$stack]($style)\]'

[purescript]
format = 'ó°” [$symbol($version)]($style)\]'

[python]
format = 'ó°” [${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
symbol = "îˆµ "

[rlang]
symbol = "ó°Ÿ” "

[raku]
format = 'ó°” [$symbol($version-$vm_version)]($style)\]'

[red]
format = 'ó°” [$symbol($version)]($style)\]'

[ruby]
format = 'ó°” [$symbol($version)]($style)\]'
symbol = "î‘ "

[rust]
format = 'ó°” [$symbol($version)]($style)\]'
symbol = "î¨ "

[scala]
format = 'ó°” [$symbol($version)]($style)\]'
symbol = "îœ· "

[spack]
format = 'ó°” [$symbol$environment]($style)\]'
symbol = "ğŸ…¢ "

[sudo]
format = 'ó°” [as $symbol]($style)\]'

[swift]
format = 'ó°” [$symbol($version)]($style)\]'

[terraform]
format = 'ó°” [$symbol$workspace]($style)\]'

[time]
format = 'ó°” [$time]($style)\]'

[username]
format = 'ó°” [$user]($style)\]'

[vagrant]
format = 'ó°” [$symbol($version)]($style)\]'

[vlang]
format = 'ó°” [$symbol($version)]($style)\]'

[zig]
format = 'ó°” [$symbol($version)]($style)\]'

[solidity]
format = 'ó°” [$symbol($version)]($style)\]'
